# Generated by Django 4.2.7 on 2023-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=1000)),
                ('mail_from', models.CharField(max_length=64)),
            ],
        ),
    ]
